name: my_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2
 

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.3.0
  get: ^4.7.2
  gap: ^3.0.1
  flutter_svg: ^2.2.0
  flutter_hooks: ^0.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  auto_route_generator: ^9.3.0
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Bold.otf

